version: "3.2"
services:
  app:
    build: .
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    ports:
      - "80:80"
  composer:
    image: composer:latest
    user: "501:20"
    command: composer install
    volumes:
      - type: bind
        source: .
        target: /app

  